// inventory
export const ADD_INVENTORY = 'ADD_INVENTORY';
export const ADD_INVENTORY_FAIL = 'ADD_INVENTORY_FAIL';
export const SORT_INVENTORY = 'SORT_INVENTORY';
export const HIGHLIGHT_INVENTORY_SPOT = 'HIGHLIGHT_INVENTORY_SPOT';

// crafting
export const ADD_CRAFTING = 'ADD_CRAFTING';
export const HIGHLIGHT_CRAFTING_SPOT = 'HIGHLIGHT_CRAFTING_SPOT';
